### ISSUE TITLE
Check availability of hashes.txt before daemonizing

### ISSUE THREAD

**Issue by joachimmetz** [rjhansen/nsrlsvr#11] opened 2016-10-15 06:32 UTC
Currently nsrlsvr daemonizes before checking if hashes.txt is available. IMO more friendly UX would be to check for the presence of hashes.txt before daemonizing and directly report to the user that file is not available, instead of having to look it up in syslog. Thanks in advance.

**Comment by rjhansen** [comment] 2016-10-15 14:29
Worse, actually -- violates the Uniform Access Principle.

The current rule is, "if nsrlsvr fails to start, it will print the reason in syslog".  Adding a special case of, "except for this one error condition, which will be handled differently" is a UX regression.

I could add a --dry-run option, which would (a) not daemonize (b) print to stderr instead of syslog and (c) abort once it stood up.  Would this be helpful?

**Comment by joachimmetz** [comment] 2016-10-15 16:25
> Worse, actually -- violates the Uniform Access Principle.

I don't follow your remark regarding UAP here

> I could add a --dry-run option, which would (a) not daemonize (b) print to stderr instead of syslog and (c) abort once it stood up

Yes, having it run in foreground to troubleshoot would be a useful feature.

**Comment by rjhansen** [comment] 2016-10-17 01:05
Progress report: works for me.  Needs more testing before it goes into --master.

Years ago I thought about whether the hashes should load before or after daemonization.  Before has the advantage of stdout still existing, so immediate feedback can be given in case of a problem.  However, there's a major problem with that -- it takes a long time to bring it up, and some init script systems will see this as evidence of a wedged process and will kill it.  So in order to make it play nice with init, it has to daemonize immediately, which means no stdout, which means it has to print to syslog.

I really wish I had written this down five years ago rather than having to relearn it the hard way tonight...

**Comment by rjhansen** [comment] 2016-10-17 01:10
(note: the dry-run option never stands the server up, so it never daemonizes, which means it can print to stdout or a logfile without running into resource contention problems.  #10 is a WONTFIX, this one is accepted.)

**Comment by joachimmetz** [comment] 2016-10-17 04:57
Sounds good, thanks

**Comment by rjhansen** [comment] 2016-10-27 14:47
Fix is in -master, but not well-tested.  Use at your own risk.  :)

**Comment by joachimmetz** [comment] 2016-10-28 05:10
thx, will try and let you know if I run into things

**Comment by rjhansen** [comment] 2016-11-17 18:24
Closed after three weeks.  I'm assuming it works well enough to be accepted.  :)

**Closed by rjhansen** 2016-11-17 18:24 UTC
Labels: enhancement
